2020-12-21 18:29:39,871 - gh.py[line:26] - ERROR: aaa
2020-12-22 12:12:54,990 - gh.py[line:317] - ERROR: Traceback (most recent call last):
  File "C:/Users/drx/Desktop/GH/GH/gh.py", line 289, in spider_gh
    WebDriverWait(driver, web_wait_time).until_not(lambda diver: driver.find_element_by_xpath('/html/body/div[6]'))
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until_not
    raise TimeoutException(message)
selenium.common.exceptions.TimeoutException: Message: 


